# TODO: Install cudf https://docs.rapids.ai/install
name: benchmark

channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - pytorch-scatter
  - pandas
